name: Unit Testing - Unity

on:
  push:
    branches: [ Poduction ]
  pull_request:
    branches: [ Production ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C 3_Implementation/ test
